### ISSUE TITLE
Can't read OVPN file

### ISSUE THREAD

**Issue by elb34st** [DyonR/docker-Jackettvpn#53]
Good day i know that you have listed this issue as closed but i'm unable i'm getting the error that the container is unable to read the OVPN file.

`Options error: In [CMD-LINE]:1: Error opening configuration file: /config/openvpn/ca1485.nordvpn.com.udp.ovpn`

I have already tried all the fixes available and without success...

Here is my docker-compose file:
```

version: '3.3'

services:
 jackettvpn:
  image: dyonr/jackettvpn
  privileged: true
  cap_add:
    - NET_ADMIN
  ports:
    - "32710:9117"
  devices:
    - /dev/net/tun
  volumes:
    - /volume1/docker/jackett:/config
  environment:
    - VPN_ENABLED=yes
    - VPN_TYPE=openvpn
    - LAN_NETWORK="172.20.10.0/24"
    - PUID=1028
    - PGID=100
    - NAME_SERVERS=1.1.1.1,9.9.9.9
  restart: unless-stopped
  network_mode: "myNet"
```

What do you think could be the issue?
