### ISSUE TITLE
PUID not found.

### ISSUE THREAD

**Issue by kiwijunglist** [DyonR/docker-Jackettvpn#8]
Hi

If i specify my PUID=1000 and GUID=1000 I get user/group not found.
I can run the container if I don't specify a user/group, in this case It runs as root:root and it works fine.
All of my other containers are working ok using the same PGID/PUID.

```
  jackett_vpn:
    container_name: jackett_vpn
    image: dyonr/jackettvpn
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=${TZ}
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - LAN_NETWORK=192.168.1.0/24
      - VPN_ENABLED=yes
      - VPN_USERNAME=xxxxxxxxxxxxxxxx
      - VPN_PASSWORD=xxxxxxxxxxxx
      - WEBUI_PORT=9117
      - PGID=${PGID}
      - PUID=${PUID}
    ports:
      - 9117:9117
    volumes:
      - ${DOCKERCONFDIR}/jackett_vpn:/config
      - ${DOCKERSHAREDDIR}:/shared
      - ${DOWNLOADSDIR}:/blackhole
```

```
...
2019-01-28 06:07:33.766085 [info] Starting Jackett daemon...
Logging to /config/Jackett/log.txt.
start-stop-daemon: user '1000' not found
2019-01-28 06:07:34.809227 [info] Jackett PID:
...
```

```
mike@server:~$ id
uid=1000(mike) gid=1000(mike) groups=1000(mike),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),108(lxd),1001(docker)

mike@server:~/.docker/config/jackett_vpn$ ls -l
total 8
drwxr-xr-x 4 mike mike 4096 Jan 27 08:43 Jackett
drwxrwxr-x 2 mike mike 4096 Jan 28 06:07 openvpn

mike@server:~/.docker/config/jackett_vpn$ find . -ls | awk '{printf "%s %s %s ", $3, $5, $6; for (i = 11; i <= NF; i++) printf "%s ", $i; printf "\n"}' | grep "^d" | cut -c 12-
mike mike .
mike mike ./openvpn
mike mike ./.mono
mike mike ./.mono/certs
mike mike ./.mono/certs/Trust
mike mike ./Jackett
mike mike ./Jackett/DataProtection
mike mike ./Jackett/Indexers
```
